using CocoNats.Abstractions.Services;

using Microsoft.Extensions.Logging;

using NATS.Client.Core;

namespace CocoNats.Core.Handlers;

public class AutoGeneratedServiceHandler<TService>(
    ILogger<AutoGeneratedServiceHandler<TService>> logger,
    INatsConnection connection,
    IServiceProvider serviceProvider
) : BaseServiceHandler<TService>(logger, connection, serviceProvider)
    where TService : class, INatsService

{

}